resources:
  - name: scriptGit
    type: GitRepo
    configuration:
      path: rahulnlb1/jfrog-infinite
      gitProvider: RahulGithub
      branches:
        include: ^{{gitBranch}}$

# pipelines:
#  - name: infinite_pipeline
#    steps:
#      - name: S_Bash_0023
#        type: Bash
#        configuration:
#          inputResources:
#             - name: scriptGit
#        execution:
#          onExecute:
#            - echo $res_scriptGit_resourcePath
#            - pushd $res_scriptGit_resourcePath
#            - chmod 777 execute.sh
#            - cat execute.sh
#            - ./execute.sh
#            - popd
           
pipelines:
  - name: pipeline_1
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: node
            versions:
              - "10.18.0"
    steps:
       - name: S_Bash_0023
         type: PowerShell
         configuration:
           inputResources:
              - name: scriptGit
         execution:
           onExecute:
              - Write-Output "Hello World"
#              - Write-Output $res_scriptGit_resourcePath
#              - Push-Location $res_scriptGit_resourcePath
#              - chmod 777 x.js
#              - node x.js
#              - Pop-Location
