resources:
  - name: scriptGit
    type: GitRepo
    configuration:
      path: rahulnlb1/jfrog-infinite
      gitProvider: Github
      branches:
        include: ^{{gitBranch}}$

pipelines:
 - name: infinite_pipeline
   steps:
     - name: S_Bash_0023
       type: Bash
       configuration:
         inputResources:
            - name: scriptGit
       execution:
         onExecute:
           - echo $res_scriptGit_resourcePath
           - pushd $res_scriptGit_resourcePath
           - chmod 777 execute.sh
           - ./execute.sh
           - popd
