resources:
  - name: scriptGit
    type: GitRepo
    configuration:
      path: rahulnlb1/jfrog-infinite
      gitProvider: Github
      branches:
        include: ^{{gitBranch}}$

pipelines:
 - name: infinite_pipeline
   steps:
     - name: S_Bash_0023
       type: Bash
       configuration:
         inputResources:
            - name: scriptGit
       execution:
         onExecute:
           - pushd $res_scriptGit_resourcePath
           - ls
           - ./execute.sh 10000000000 101
           - popd
